CREATE TABLE STUDENTS (
  STUDENT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROLL_NUMBER       VARCHAR2(20) NOT NULL UNIQUE,
  STUDENT_NAME      VARCHAR2(100) NOT NULL,
  CGPA              NUMBER(3,2),
  ATTENDANCE_PCT    NUMBER(5,2),
  ASSIGNMENT_MARKS  NUMBER(5,2),
  CLASS_BEHAVIOR    NUMBER(1) CHECK (CLASS_BEHAVIOR BETWEEN 1 AND 5),
  LAB_BEHAVIOR      NUMBER(1) CHECK (LAB_BEHAVIOR BETWEEN 1 AND 5),
  CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PREDICTIONS (
  PREDICTION_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_ID        NUMBER REFERENCES STUDENTS(STUDENT_ID),
  RISK_LEVEL        VARCHAR2(20) CHECK (RISK_LEVEL IN ('DANGER', 'ATTENTION', 'CLEAR')),
  RISK_SCORE        NUMBER(5,2),
  AI_SUGGESTIONS    CLOB,
  PREDICTED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
